apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: clase7
  namespace: clase7
spec:
  selector:
    matchLabels:
      app: clase7
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: clase7
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: root_password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_name
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: user_password
        - name: MYSQL_DATABASE
          value: 'aws101'
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-data-disk
