apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: clase3-deployment
  labels:
    app: clase3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clase3
  template:
    metadata:
      labels:
        app: clase3
    spec:
      containers:
        - name: hola-aws101
          image: dolguin/hola-aws101:latest
          ports:
            - name: web
              containerPort: 80
              protocol: TCP